export const CHANGE_TO_RECOMMEND = 'RECOMMEND/CHANGE_TO_RECOMMEND'

export const CHANGE_TO_BANNDER = 'RECOMMEND/CHANGE_TO_BANNDER'

export const CHANGE_NEW_ALBUM = 'RECOMMEND/CHANGE_NEW_ALBUM'

export const CHANGE_UP_LIST = 'RECOMMEND/CHANGE_UP_LIST'

export const CHANGE_NEW_LIST = 'RECOMMEND/CHANGE_NEW_LIST'

export const CHANGE_ORIGIN_LIST = 'RECOMMEND/CHANGE_ORIGIN_LIST'
